# Application Configuration

# Database file record id on Zenodo
project_data:
  record_id: "3887306"
  file_name: "building-data-genome-project-2-v1.0.zip"
  raw_data_file_path: "./data_sources/raw_data"
  zip_file_folders_to_extract: ['raw', 'metadata', 'weather']
  schemas_dir_path: "./schemas"
  temp_dir_path: "./tmp"
  unique_columns: {'metadata': ['building_id'],
                   'weather': ['timestamp', 'site_id'],
                   'raw': ['timestamp', 'building_id', 'meter']}

staging_database:
  host: "localhost"
  port: 5432
  database: "building_energy_staging_db_v2"
  user: "postgres"
  password: "postgres"

database:
  host: "localhost"
  port: 5432
  database: "building_energy_db_v2"
  user: "postgres"
  password: "postgres"

default_database:
  host: "localhost"
  port: 5432
  database: "postgres"
  user: "postgres"
  password: "postgres"

